import assert from 'node:assert/strict';
import { once } from 'node:events';
import { randomUUID } from 'node:crypto';
import express from 'express';
import { hashPassword, verifyPassword } from './password.js';

const password = 'test-password-with-spaces 123!';
const hash = await hashPassword(password);
assert.equal(await verifyPassword(password, hash), true);
assert.equal(await verifyPassword('wrong', hash), false);
assert.equal(await verifyPassword(password, 'invalid'), false);
process.env.ADMIN_USERNAME = 'auth-test';
process.env.ADMIN_PASSWORD_HASH = hash;
process.env.QUEUE_PREFIX = `mso-auth-test-${randomUUID()}`;
const { authRouter } = await import('./auth.routes.js');
const { authRedis, sessionKey } = await import('./session.js');
const { apiKeyAuth } = await import('../../http/middleware/auth.js');
const { env } = await import('../../config/env.js');
if (authRedis.status !== 'ready') await once(authRedis, 'ready');
const app = express();
app.use(express.json());
app.use('/auth', authRouter);
app.all('/admin', apiKeyAuth(), (req, res) => res.json({ role: req.role, operator: req.operator }));
app.get('/wms', apiKeyAuth('TERMINAL'), (req, res) => res.json({ role: req.role }));
const server = app.listen(0, '127.0.0.1');
await once(server, 'listening');
const address = server.address();
assert(address && typeof address !== 'string');
const base = `http://127.0.0.1:${address.port}`;
const login = (body: unknown, client = true) => fetch(`${base}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json', ...(client ? { 'x-mso-client': 'web' } : {}) }, body: JSON.stringify(body) });
try {
  assert.equal((await fetch(`${base}/admin`)).status, 401);
  assert.equal((await fetch(`${base}/wms`)).status, 401);
  assert.equal((await login({ username: env.ADMIN_USERNAME, password }, false)).status, 403);
  assert.equal((await login({ username: env.ADMIN_USERNAME, password: 'incorrect' })).status, 401);
  assert.equal((await login({ username: 'another-user', password })).status, 401);
  assert.equal((await login({})).status, 400);
  const response = await login({ username: env.ADMIN_USERNAME, password });
  assert.equal(response.status, 200);
  const cookieHeader = response.headers.get('set-cookie')!;
  assert.match(cookieHeader, /HttpOnly/i);
  assert.match(cookieHeader, /SameSite=Strict/i);
  const cookie = cookieHeader.split(';')[0]!;
  const headers = { cookie, 'x-mso-client': 'web' };
  const me = await fetch(`${base}/auth/me`, { headers });
  assert.equal(me.status, 200);
  assert.equal(me.headers.get('cache-control'), 'no-store');
  const admin = await fetch(`${base}/admin`, { headers: { ...headers, 'x-operator': 'forged' } });
  assert.deepEqual(await admin.json(), { role: 'ADMIN', operator: env.ADMIN_USERNAME });
  assert.equal((await fetch(`${base}/wms`, { headers })).status, 200);
  assert.equal((await fetch(`${base}/admin`, { method: 'POST', headers: { cookie } })).status, 403);
  assert.equal((await fetch(`${base}/admin`, { method: 'POST', headers })).status, 200);
  assert.equal((await fetch(`${base}/auth/logout`, { method: 'POST', headers })).status, 204);
  assert.equal((await fetch(`${base}/admin`, { headers })).status, 401);
  const expiry = await login({ username: env.ADMIN_USERNAME, password });
  const expiredCookie = expiry.headers.get('set-cookie')!.split(';')[0]!;
  await authRedis.del(sessionKey(expiredCookie.split('=')[1]!));
  assert.equal((await fetch(`${base}/admin`, { headers: { cookie: expiredCookie } })).status, 401);
  assert.equal((await fetch(`${base}/admin`, { headers: { 'x-api-key': env.TERMINAL_API_KEY } })).status, 403);
  assert.equal((await fetch(`${base}/wms`, { headers: { 'x-api-key': env.TERMINAL_API_KEY } })).status, 200);
  for (let i = 0; i < 10; i++) assert.equal((await login({ username: env.ADMIN_USERNAME, password: 'bad' })).status, 401);
  assert.equal((await login({ username: env.ADMIN_USERNAME, password })).status, 429);
  console.log('Auth integration checks passed: password hashing, login validation, protected routes, cookie flags, operator identity, CSRF header, logout/revocation, expiry, roles and rate limiting.');
} finally {
  const keys = await authRedis.keys(`${env.QUEUE_PREFIX}:auth:*`);
  if (keys.length) await authRedis.del(...keys);
  await authRedis.quit();
  await new Promise<void>((resolve, reject) => server.close(err => err ? reject(err) : resolve()));
}
